language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
matrix:
  # pypy3 (as of 2.4.0) has a wacky arity issue in its source loader. Allow it
  # to fail until we can test on, and require, PyPy3.3+. See invoke#358.
  allow_failures:
    - python: pypy3
  fast_finish: true
install:
  # Install deps + self
  - pip install -r dev-requirements.txt
  # Forcibly uninstall enum34 if on python 3.6; otherwise it can gum
  # up things like the re module. (invocations' setup.py tries to do this for
  # us, but wheels don't give a fuck.)
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6']]; then pip uninstall -y enum34; fi"
  # Sanity test
  - inv --list
script:
  # Run tests, generating coverage report (skipping html+open).
  - inv coverage --no-html
  # Did we break setup.py?
  - pip uninstall -y pytest-relaxed # To undo the implicit -e install
  - pip install . # NO -e!
  # Run our own tests again as our sanity test; don't see another way of asking
  # pytest to print its plugin list (as with fixtures/markers) :(
  - "pytest | grep 'plugins: relaxed'"
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
after_success:
  # Upload coverage data to codecov
  - codecov
notifications:
  # TODO: this is basically the default, but most of my other projects have
  # customizations here, I may want some eventually too?
  email: true
